repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
        args: [ "--workspace" ]
      - id: fmt
        args: [ "--", "--check" ]
      - id: clippy
        args: [ "--", "-D", "warnings" ]
  - repo: local
    hooks:
      - id: check-license-header
        name: Check License Header
        entry: ./check_license.sh
        language: script
        files: \.rs$