[workspace]
members = [
    "crates/utils",
    "crates/catalog",
    "crates/control_plane", 
    "crates/nexus",
]
resolver= "2"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = { version = "0.3" }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
axum = { version = "0.7" }
axum-macros = "0.4"
tokio = { version = "1", features = ["full"] }
async-trait = { version = "0.1" }
serde = { version = "1.0", features = ["derive"] }
slatedb = { version = "*" }
bytes = { version = "1" }
object_store = { version = "0.11" }
serde_json = "1.0"
serde_yaml = "0.8"
tower = { version = "0.4", features = ["util"] }
http-body-util = "0.1.0"
thiserror = { version = "1" }
iceberg = { git = "https://github.com/hansetag/iceberg-rust.git", branch = "ct/builder-upstream-20241002" }
iceberg-catalog-memory = { version = "0.3" }
tempfile = { version = "3" }
utoipa = { version = "5.0.0-beta.0", features = ["uuid", "chrono"] }
utoipa-axum = { version = "0.1.0-beta.2" }
utoipa-swagger-ui = { version = "7.1.1-beta.0", features = ["axum"] }
lazy_static = { version = "1.5" }
