[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
  "MPL-2.0",
  "ISC",
  "CC0-1.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "OpenSSL",
  "Zlib",
  "BSL-1.0"
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]