[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
object_store = { workspace = true }
tracing = { workspace = true }

datafusion = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-common = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-expr = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }

arrow = { version = "54.1.0" }
arrow-json = { version = "54.1.0" }
arrow-schema = { version = "54.1.0", default-features = false }


sqlparser = { git = "https://github.com/Embucket/datafusion-sqlparser-rs.git", rev = "53c291e3e95f176daea954f614409e5f674ec561", features = [
  "visitor",
] }
regex = { version = "1.11.0" }

paste = "1"
snafu = { workspace = true }
url = { version = "2.5.4" }
datafusion-functions-json = { git = "https://github.com/Embucket/datafusion-functions-json.git", rev = "9e9bd378b979a6b7081cf278c54a76eb94b00fc5" }

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1.42.0", features = ["yaml"] }
