[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]

arrow = { version = "54.1.0" }
arrow-json = { version = "54.1.0" }
arrow-schema = { version = "54.1.0", default-features = false }
async-trait = { workspace = true }

chrono = { workspace = true }

datafusion = { git = "https://github.com/Embucket/datafusion.git", rev = "2950e0be59f81fbd6593f7457f1f03e63a292820" }
datafusion-common = { git = "https://github.com/Embucket/datafusion.git", rev = "2950e0be59f81fbd6593f7457f1f03e63a292820" }
datafusion-expr = { git = "https://github.com/Embucket/datafusion.git", rev = "2950e0be59f81fbd6593f7457f1f03e63a292820" }
datafusion-functions-json = { git = "https://github.com/Embucket/datafusion-functions-json.git", rev = "a5bbbd1266447c26f3bfdb5314b4a326796bc784" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "f2fef1d973f59309919d60aaaa32e83e04029d6d" }
futures = { workspace = true }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "f2fef1d973f59309919d60aaaa32e83e04029d6d" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "f2fef1d973f59309919d60aaaa32e83e04029d6d" }
object_store = { workspace = true }

paste = "1"
regex = { version = "1.11.0" }
serde = { workspace = true }
serde_json = { workspace = true }
snafu = { workspace = true }

sqlparser = { git = "https://github.com/Embucket/datafusion-sqlparser-rs.git", rev = "53c291e3e95f176daea954f614409e5f674ec561", features = [
  "visitor",
] }
tokio = { workspace = true }
tracing = { workspace = true }
url = { version = "2.5.4" }
uuid = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
insta = { version = "1.42.0", features = ["yaml"] }
