[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
object_store = { workspace = true }
tracing = { workspace = true}

datafusion = { git="https://github.com/Embucket/datafusion.git", rev = "818728a8aeea971546241aa19af35c74bc361d50" }
datafusion-common = { git="https://github.com/Embucket/datafusion.git", rev = "818728a8aeea971546241aa19af35c74bc361d50" }
datafusion-expr = { git="https://github.com/Embucket/datafusion.git", rev = "818728a8aeea971546241aa19af35c74bc361d50" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "294df8b4a21bbee99e7d335c9d8f5bbcb40f500f" }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "294df8b4a21bbee99e7d335c9d8f5bbcb40f500f" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "294df8b4a21bbee99e7d335c9d8f5bbcb40f500f" }

arrow = { version = "53" }
arrow-json = { version = "53" }
arrow-schema = { version = "53.3.0", default-features = false }

datafusion-functions-json = { version = "0.44.0" }
sqlparser = { version = "0.53.0", features = ["visitor"] }
regex = { version = "1.11.0" }

paste = "1"
snafu = { workspace = true }
url = { version = "2.5.4" }

[lints]
workspace = true

[dev-dependencies]
insta = { version="1.42.0", features=["yaml"] }