[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
object_store = { workspace = true }

datafusion = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }
datafusion-common = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }
datafusion-expr = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "68577441273eda894f1eb6d87b1c3e87dee0fdf6" }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "68577441273eda894f1eb6d87b1c3e87dee0fdf6" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "68577441273eda894f1eb6d87b1c3e87dee0fdf6" }

arrow = { version = "53" }
arrow-json = { version = "53" }
arrow-schema = { version = "53.3.0", default-features = false }

datafusion-functions-json = { version = "0.44.0" }
sqlparser = { version = "0.53.0", features = ["visitor"] }
regex = { version = "1.11.0" }

paste = "1"
snafu = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
insta = "1.42.0"