[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]

arrow = { version = "54.1.0" }
arrow-json = { version = "54.1.0" }
async-trait = { workspace = true }
base64 = { version = "0.22.1" }
bytes = { version = "1.8.0" }

chrono = { workspace = true }
#iceberg-rust = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#iceberg-rest-catalog = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#datafusion_iceberg = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }

datafusion = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-common = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-expr = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-functions-json = { git = "https://github.com/Embucket/datafusion-functions-json.git", rev = "9e9bd378b979a6b7081cf278c54a76eb94b00fc5" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
flatbuffers = { version = "24.3.25" }
futures = { workspace = true }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
icelake = { git = "https://github.com/Embucket/icelake.git", rev = "b4cbcaf" }

object_store = { workspace = true }
once_cell = "1.19.0"
quick-xml = { version = "0.36.2" }
regex = { version = "1.11.0" }
runtime = { path = "../runtime" }
rusoto_core = { version = "0.48.0" }
rusoto_credential = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
serde = { workspace = true }
serde_json = "1.0.128"
snafu = { workspace = true }
strum = { version = "0.26.3", features = ["derive"] }
tokio = { workspace = true }
tracing = { version = "0.1" }
url = { version = "2.5.2" }
utils = { path = "../utils" }
uuid = { workspace = true }

[dev-dependencies]
slatedb = { workspace = true }

[lints]
workspace = true
