[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
datafusion = { version = "41" }
iceberg-catalog-rest = { version = "0.3" }
iceberg-datafusion = { version = "0.3" }
arrow = { version = "52" }

[dev-dependencies]
slatedb = {workspace = true }
object_store = { workspace = true }
