[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
datafusion = { workspace = true }
iceberg-rust = { git = "https://github.com/JanKaul/iceberg-rust.git"}
iceberg-rest-catalog = { git = "https://github.com/JanKaul/iceberg-rust.git"}
datafusion_iceberg = { git = "https://github.com/JanKaul/iceberg-rust.git"}
arrow = { version = "53" }
arrow-json = { version = "53" }
datafusion-functions-json = { version = "0.43.0" }
object_store = { workspace = true }
dotenv = { workspace = true }
rusoto_core = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
rusoto_credential = { version = "0.48.0" }
quick-xml = { version = "0.36.2" }
icelake = { git = "https://github.com/Embucket/icelake.git" }
bytes = { version = "1.8.0" }
url = { version = "2.5.2" }

[dev-dependencies]
slatedb = { workspace = true }
