[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
datafusion = { workspace = true }
datafusion-functions-json = { version = "0.40.0" }
iceberg-rust = { version = "0.5.8" }
iceberg-rest-catalog = { version = "0.5.8" }
datafusion_iceberg = { version = "0.5.8" }
arrow = { version = "52" }
arrow-json = { version = "52" }
object_store = { workspace = true }
object_store_for_slatedb = { workspace = true }
dotenv = { workspace = true }
rusoto_core = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
rusoto_credential = { version = "0.48.0" }
quick-xml = { version = "0.36.2" }
icelake = { git = "https://github.com/Embucket/icelake.git" }
bytes = { version = "1.8.0" }

[dev-dependencies]
slatedb = { workspace = true }
