[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = {path = "../runtime"}

chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
flatbuffers = { version = "24.3.25" }
#iceberg-rust = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#iceberg-rest-catalog = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#datafusion_iceberg = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }

datafusion = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }
datafusion-common = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }
datafusion-expr = { git="https://github.com/Embucket/datafusion.git", rev = "cc37c5920463b0cb0b224fc7f567fd4ae0368ffe" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "09090f0e9b11153a549ed447581a5b595484b245" }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "09090f0e9b11153a549ed447581a5b595484b245" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "09090f0e9b11153a549ed447581a5b595484b245" }

arrow = { version = "53" }
arrow-json = { version = "53" }
datafusion-functions-json = { version = "0.43.0" }
object_store = { workspace = true }
dotenv = { workspace = true }
rusoto_core = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
rusoto_credential = { version = "0.48.0" }
quick-xml = { version = "0.36.2" }
icelake = { git = "https://github.com/Embucket/icelake.git", rev="b4cbcaf" }
bytes = { version = "1.8.0" }
url = { version = "2.5.2" }
serde_json = "1.0.128"
once_cell = "1.19.0"
regex = { version = "1.11.0" }
base64 = { version = "0.22.1" }
snafu = { workspace = true }
strum = { version = "0.26.3", features = ["derive"] }

[dev-dependencies]
slatedb = { workspace = true }

[lints]
workspace = true
