[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
datafusion = { version = "40" }
iceberg-rust = { version = "0.5.8" }
iceberg-rest-catalog = { version = "0.5.8" }
datafusion_iceberg = { version = "0.5.8" }
arrow = { version = "52" }
arrow-json = { version = "52" }
object_store = { workspace = true }

[dev-dependencies]
slatedb = {workspace = true }
