[package]
name = "control_plane"
version = "0.1.0"
edition = "2021"

[dependencies]
runtime = { path = "../runtime" }

chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
utils = { path = "../utils" }
futures = { workspace = true }
serde = { workspace = true }
flatbuffers = { version = "24.3.25" }
#iceberg-rust = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#iceberg-rest-catalog = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }
#datafusion_iceberg = { git = "https://github.com/JanKaul/iceberg-rust.git", rev = "836f11f" }

datafusion = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-common = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }
datafusion-expr = { git = "https://github.com/Embucket/datafusion.git", rev = "a4c5f3f065b551afdf845000e3630012af27dc17" }

iceberg-rust = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
iceberg-rest-catalog = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }
datafusion_iceberg = { git = "https://github.com/Embucket/iceberg-rust.git", rev = "c5d3eb7a19c2777a8843a454a1a42cad3bec61d1" }

arrow = { version = "54.1.0" }
arrow-json = { version = "54.1.0" }

object_store = { workspace = true }
rusoto_core = { version = "0.48.0" }
rusoto_s3 = { version = "0.48.0" }
rusoto_credential = { version = "0.48.0" }
quick-xml = { version = "0.36.2" }
icelake = { git = "https://github.com/Embucket/icelake.git", rev = "b4cbcaf" }
bytes = { version = "1.8.0" }
url = { version = "2.5.2" }
serde_json = "1.0.128"
once_cell = "1.19.0"
regex = { version = "1.11.0" }
base64 = { version = "0.22.1" }
snafu = { workspace = true }
strum = { version = "0.26.3", features = ["derive"] }
tracing = { version = "0.1" }
datafusion-functions-json = { git = "https://github.com/Embucket/datafusion-functions-json.git", rev = "9e9bd378b979a6b7081cf278c54a76eb94b00fc5" }

[dev-dependencies]
slatedb = { workspace = true }

[lints]
workspace = true
