[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
slatedb = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
iceberg = { workspace = true }
uuid = { workspace = true }
snafu = { workspace = true }

[lints]
workspace = true