[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
slatedb = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
iceberg = { workspace = true }