[package]
name = "visitors"
version = "0.1.0"
edition = "2024"
license-file.workspace = true

[dependencies]
datafusion = { workspace = true }
datafusion-expr = { workspace = true }
datafusion-common = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
