#!/usr/bin/env python3
"""
Test script for the Snowflake query execution tool.
"""

import json
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Import the Snowflake tools
from tools.snowflake_query_execution_tool import (
    execute_query_against_snowflake,
    validate_snowflake_connection
)


def test_snowflake_connection():
    """Test the Snowflake connection validation."""
    print("=== Testing Snowflake Connection Validation ===")
    
    result = validate_snowflake_connection()
    result_data = json.loads(result)
    
    print(f"Connection validation result: {result_data}")
    
    if result_data['success']:
        print("✓ Snowflake connection validation successful")
        return True
    else:
        print(f"✗ Snowflake connection validation failed: {result_data['message']}")
        return False


def test_simple_query():
    """Test a simple SELECT query."""
    print("\n=== Testing Simple Query Execution ===")
    
    # Test with a simple query
    test_query = "SELECT 1 as test_column, 'Hello Snowflake' as message"
    
    result = execute_query_against_snowflake(test_query)
    result_data = json.loads(result)
    
    print(f"Query execution result: {result_data}")
    
    if result_data['success']:
        print("✓ Simple query execution successful")
        print(f"  Query ID: {result_data.get('query_id', 'N/A')}")
        print(f"  Rows returned: {result_data.get('rows_affected', 0)}")
        print(f"  Execution time: {result_data.get('execution_time', 0):.3f}s")
        if result_data.get('result_data'):
            print(f"  Sample data: {result_data['result_data'][:2]}")  # Show first 2 rows
        return True
    else:
        print(f"✗ Simple query execution failed: {result_data['error_message']}")
        return False


def test_complex_query():
    """Test a more complex query that might be used in fuzzing."""
    print("\n=== Testing Complex Query Execution ===")
    
    # Test with a query similar to what might be generated by the fuzzing agent
    test_query = """
    WITH test_cte AS (
        SELECT 
            1 as id,
            'test' as name,
            CURRENT_TIMESTAMP() as created_at
        UNION ALL
        SELECT 
            2 as id,
            'another_test' as name,
            CURRENT_TIMESTAMP() as created_at
    )
    SELECT 
        id,
        name,
        created_at,
        COUNT(*) OVER() as total_count
    FROM test_cte
    ORDER BY id
    """
    
    result = execute_query_against_snowflake(test_query)
    result_data = json.loads(result)
    
    print(f"Complex query execution result summary:")
    print(f"  Success: {result_data['success']}")
    print(f"  Query ID: {result_data.get('query_id', 'N/A')}")
    print(f"  Rows returned: {result_data.get('rows_affected', 0)}")
    print(f"  Execution time: {result_data.get('execution_time', 0):.3f}s")
    
    if result_data.get('compilation_time') is not None:
        print(f"  Compilation time: {result_data['compilation_time']:.2f}ms")
    if result_data.get('total_elapsed_time') is not None:
        print(f"  Total elapsed time: {result_data['total_elapsed_time']:.2f}ms")
    
    if result_data['success']:
        print("✓ Complex query execution successful")
        if result_data.get('result_data'):
            print(f"  Sample data: {result_data['result_data'][:2]}")  # Show first 2 rows
        return True
    else:
        print(f"✗ Complex query execution failed: {result_data['error_message']}")
        return False


def test_error_handling():
    """Test error handling with an invalid query."""
    print("\n=== Testing Error Handling ===")
    
    # Test with an intentionally invalid query
    invalid_query = "SELECT * FROM non_existent_table_12345"
    
    result = execute_query_against_snowflake(invalid_query)
    result_data = json.loads(result)
    
    print(f"Error handling test result:")
    print(f"  Success: {result_data['success']}")
    print(f"  Error type: {result_data.get('error_type', 'N/A')}")
    print(f"  Error message: {result_data.get('error_message', 'N/A')[:100]}...")
    
    if not result_data['success'] and result_data.get('error_type'):
        print("✓ Error handling working correctly")
        return True
    else:
        print("✗ Error handling not working as expected")
        return False


def main():
    """Run all tests."""
    print("Testing Snowflake Query Execution Tool")
    print("=" * 50)
    
    # Check if Snowflake configuration is available
    required_env_vars = ['SNOWFLAKE_ACCOUNT', 'SNOWFLAKE_USER', 'SNOWFLAKE_PASSWORD']
    missing_vars = [var for var in required_env_vars if not os.getenv(var)]
    
    if missing_vars:
        print(f"⚠️  Missing required environment variables: {', '.join(missing_vars)}")
        print("Please set these in your .env file to run the tests.")
        print("\nExample .env configuration:")
        print("SNOWFLAKE_ACCOUNT=your_account")
        print("SNOWFLAKE_USER=your_username")
        print("SNOWFLAKE_PASSWORD=your_password")
        print("SNOWFLAKE_WAREHOUSE=COMPUTE_WH")
        print("SNOWFLAKE_DATABASE=your_database")
        print("SNOWFLAKE_SCHEMA=public")
        return
    
    # Run tests
    tests = [
        test_snowflake_connection,
        test_simple_query,
        test_complex_query,
        test_error_handling
    ]
    
    passed = 0
    total = len(tests)
    
    for test in tests:
        try:
            if test():
                passed += 1
        except Exception as e:
            print(f"✗ Test {test.__name__} failed with exception: {e}")
    
    print(f"\n=== Test Results ===")
    print(f"Passed: {passed}/{total}")
    
    if passed == total:
        print("🎉 All tests passed!")
    else:
        print(f"⚠️  {total - passed} test(s) failed")


if __name__ == "__main__":
    main()
