[package]
name = "bucketd"
version = "0.1.0"
edition = "2021"
license-file = { workspace = true }

[dependencies]
clap = { version = "4.5.27", features = ["env", "derive"] }
dotenv = { version = "0.15.0" }
icebucket_runtime = { path = "../../crates/runtime" }
object_store = { workspace = true }
snmalloc-rs = { workspace = true }
strum = { version = "0.27.1", features = ["derive"] }
tokio = { workspace = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints]
workspace = true
