[package]
name = "nexus"
version = "0.1.0"
edition = "2021"

[build-dependencies]
utoipa = { workspace = true }

[dependencies]
axum = { workspace = true }
axum-macros = { workspace = true }
tokio = { workspace = true }
control_plane = { path = "../control_plane" }
catalog = { path = "../catalog" }
chrono = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serde = { workspace = true }
iceberg = { workspace = true }
slatedb = { workspace = true }
object_store = { workspace = true }
utils = { path = "../utils" }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
utoipa-swagger-ui = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
async-trait = { workspace = true }
http-body-util = { workspace = true }
tempfile = { workspace = true }
lazy_static = { workspace = true }
