# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several checks:
# - fmt: checks that the code is formatted according to rustfmt
# - clippy: checks that the code does not contain any clippy warnings
# - doc: checks that the code can be documented without errors
# - hack: check combinations of feature flags
# - msrv: check that the msrv specified in the crate is correct
permissions:
  contents: read
# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [main]
    paths:
      - crates/**
      - bin/**
      - ui/**
  pull_request:
    paths:
      - crates/**
      - bin/**
      - ui/**
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: license_check
jobs:
  license_check:
    runs-on: ubuntu-latest
    name: Check license headers
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Check license headers
        uses: viperproject/check-license-header@v2
        with:
          config: .check-license.config.json
          strict: false
