name: rustdoc comments

on:
  pull_request:
    branches:
      - yaro/sqlite-metastore
      
env:
  CARGO_TERM_COLOR: always

jobs:
  run_patchdog:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - name: Patchdog
        uses: YuraLitvinov/patchdog@v1.2.62
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key_gemini: ${{ secrets.API_KEY_GEMINI }}